!function(i){"function"==typeof define&&define.amd?define(i):i()}((function(){"use strict";var i,n,t;i=function(){
/**
          * @license
          * Copyright 2017 Google LLC
          * SPDX-License-Identifier: BSD-3-Clause
          */
var i,n,t="__scoped";null!==(i=(n=globalThis).reactiveElementPlatformSupport)&&void 0!==i||(n.reactiveElementPlatformSupport=function(i){var n=i.ReactiveElement,o=window;if(void 0!==o.ShadyCSS&&(!o.ShadyCSS.nativeShadow||o.ShadyCSS.ApplyShim)){var e=n.prototype;o.ShadyDOM&&o.ShadyDOM.inUse&&!0===o.ShadyDOM.noPatch&&o.ShadyDOM.patchElementProto(e);var v=e.createRenderRoot;e.createRenderRoot=function(){var i,n,e,r=this.localName;if(o.ShadyCSS.nativeShadow)return v.call(this);if(!this.constructor.hasOwnProperty(t)){this.constructor[t]=!0;var u=this.constructor.elementStyles.map((function(i){return i instanceof CSSStyleSheet?Array.from(i.cssRules).reduce((function(i,n){return i+n.cssText}),""):i.cssText}));null===(n=null===(i=o.ShadyCSS)||void 0===i?void 0:i.ScopingShim)||void 0===n||n.prepareAdoptedCssText(u,r),void 0===this.constructor.ΞJ&&o.ShadyCSS.prepareTemplateStyles(document.createElement("template"),r)}return null!==(e=this.shadowRoot)&&void 0!==e?e:this.attachShadow(this.constructor.shadowRootOptions)};var r=e.connectedCallback;e.connectedCallback=function(){r.call(this),this.hasUpdated&&o.ShadyCSS.styleElement(this)};var u=e.ΞE;e.ΞE=function(i){var n=!this.hasUpdated;u.call(this,i),n&&o.ShadyCSS.styleElement(this)}}})},"function"==typeof define&&define.amd?define(i):i(),function(i){"function"==typeof define&&define.amd?define(i):i()}((function(){
/**
          * @license
          * Copyright 2017 Google LLC
          * SPDX-License-Identifier: BSD-3-Clause
          */
var i,n,t=new Set,o=new Map;null!==(i=(n=globalThis).litHtmlPlatformSupport)&&void 0!==i||(n.litHtmlPlatformSupport=function(i,n){var e=window;if(void 0!==e.ShadyCSS&&(!e.ShadyCSS.nativeShadow||e.ShadyCSS.ApplyShim)){var v=function(i){var n=o.get(i);return void 0===n&&o.set(i,n=[]),n},r=new Map,u=i.createElement;i.createElement=function(n,t){var o=u.call(i,n,t),r=null==t?void 0:t.scope;if(void 0!==r){e.ShadyCSS.nativeShadow||e.ShadyCSS.prepareTemplateDom(o,r);var d=v(r),f=o.content.querySelectorAll("style");d.push.apply(d,Array.from(f).map((function(i){var n;return null===(n=i.parentNode)||void 0===n||n.removeChild(i),i.textContent})))}return o};var d=document.createDocumentFragment(),f=document.createComment(""),s=n.prototype,a=s.ΞI;s.ΞI=function(i,n){var r,u,s;void 0===n&&(n=this);var l,h=this.ΞA.parentNode,c=null===(r=this.options)||void 0===r?void 0:r.scope;if(h instanceof ShadowRoot&&void 0!==(l=c)&&!t.has(l)){var w=this.ΞA,y=this.ΞB;d.appendChild(f),this.ΞA=f,this.ΞB=null,a.call(this,i,n);var p=(null===(u=i)||void 0===u?void 0:u._$litType$)?this.ΞH.ΞD.el:document.createElement("template");if(function(i,n){var r=v(i),u=0!==r.length;if(u){var d=document.createElement("style");d.textContent=r.join("\n"),n.content.appendChild(d)}t.add(i),o.delete(i),e.ShadyCSS.prepareTemplateStyles(n,i),u&&e.ShadyCSS.nativeShadow&&n.content.appendChild(n.content.querySelector("style"))}(c,p),d.removeChild(f),null===(s=e.ShadyCSS)||void 0===s?void 0:s.nativeShadow){var m=p.content.querySelector("style");null!==m&&d.appendChild(m.cloneNode(!0))}h.insertBefore(d,y),this.ΞA=w,this.ΞB=y}else a.call(this,i,n)},s.ΞC=function(n){var t,o=null===(t=this.options)||void 0===t?void 0:t.scope,e=r.get(o);void 0===e&&r.set(o,e=new Map);var v=e.get(n.strings);return void 0===v&&e.set(n.strings,v=new i(n,this.options)),v}}})})),null!==(n=(t=globalThis).litElementPlatformSupport)&&void 0!==n||(t.litElementPlatformSupport=function(i){var n=i.LitElement,t=window;if(void 0!==t.ShadyCSS&&(!t.ShadyCSS.nativeShadow||t.ShadyCSS.ApplyShim)){n.ΞJ=!0;var o=n.prototype,e=o.createRenderRoot;o.createRenderRoot=function(){return this.renderOptions.scope=this.localName,e.call(this)}}})}));
//# sourceMappingURL=polyfill-support.js.map
