!function(i){"function"==typeof define&&define.amd?define(i):i()}((function(){"use strict";var i;i=function(){var i,n,t;i=function(){
/**
                    * @license
                    * Copyright 2017 Google LLC
                    * SPDX-License-Identifier: BSD-3-Clause
                    */
var i,n,t="__scoped";null!==(i=(n=globalThis).reactiveElementPlatformSupport)&&void 0!==i||(n.reactiveElementPlatformSupport=function(i){var n=i.ReactiveElement,o=window;if(void 0!==o.ShadyCSS&&(!o.ShadyCSS.nativeShadow||o.ShadyCSS.ApplyShim)){var e=n.prototype;o.ShadyDOM&&o.ShadyDOM.inUse&&!0===o.ShadyDOM.noPatch&&o.ShadyDOM.patchElementProto(e);var v=e.createRenderRoot;e.createRenderRoot=function(){var i,n,e,u=this.localName;if(o.ShadyCSS.nativeShadow)return v.call(this);if(!this.constructor.hasOwnProperty(t)){this.constructor[t]=!0;var r=this.constructor.elementStyles.map((function(i){return i instanceof CSSStyleSheet?Array.from(i.cssRules).reduce((function(i,n){return i+n.cssText}),""):i.cssText}));null===(n=null===(i=o.ShadyCSS)||void 0===i?void 0:i.ScopingShim)||void 0===n||n.prepareAdoptedCssText(r,u),void 0===this.constructor.ΞJ&&o.ShadyCSS.prepareTemplateStyles(document.createElement("template"),u)}return null!==(e=this.shadowRoot)&&void 0!==e?e:this.attachShadow(this.constructor.shadowRootOptions)};var u=e.connectedCallback;e.connectedCallback=function(){u.call(this),this.hasUpdated&&o.ShadyCSS.styleElement(this)};var r=e.ΞE;e.ΞE=function(i){var n=!this.hasUpdated;r.call(this,i),n&&o.ShadyCSS.styleElement(this)}}})},"function"==typeof define&&define.amd?define(i):i(),function(i){"function"==typeof define&&define.amd?define(i):i()}((function(){
/**
                    * @license
                    * Copyright 2017 Google LLC
                    * SPDX-License-Identifier: BSD-3-Clause
                    */
var i,n,t=new Set,o=new Map;null!==(i=(n=globalThis).litHtmlPlatformSupport)&&void 0!==i||(n.litHtmlPlatformSupport=function(i,n){var e=window;if(void 0!==e.ShadyCSS&&(!e.ShadyCSS.nativeShadow||e.ShadyCSS.ApplyShim)){var v=function(i){var n=o.get(i);return void 0===n&&o.set(i,n=[]),n},u=new Map,r=i.createElement;i.createElement=function(n,t){var o=r.call(i,n,t),u=null==t?void 0:t.scope;if(void 0!==u){e.ShadyCSS.nativeShadow||e.ShadyCSS.prepareTemplateDom(o,u);var f=v(u),d=o.content.querySelectorAll("style");f.push.apply(f,Array.from(d).map((function(i){var n;return null===(n=i.parentNode)||void 0===n||n.removeChild(i),i.textContent})))}return o};var f=document.createDocumentFragment(),d=document.createComment(""),s=n.prototype,a=s.ΞI;s.ΞI=function(i,n){var u,r,s;void 0===n&&(n=this);var l,h=this.ΞA.parentNode,c=null===(u=this.options)||void 0===u?void 0:u.scope;if(h instanceof ShadowRoot&&void 0!==(l=c)&&!t.has(l)){var w=this.ΞA,y=this.ΞB;f.appendChild(d),this.ΞA=d,this.ΞB=null,a.call(this,i,n);var p=(null===(r=i)||void 0===r?void 0:r._$litType$)?this.ΞH.ΞD.el:document.createElement("template");if(function(i,n){var u=v(i),r=0!==u.length;if(r){var f=document.createElement("style");f.textContent=u.join("\n"),n.content.appendChild(f)}t.add(i),o.delete(i),e.ShadyCSS.prepareTemplateStyles(n,i),r&&e.ShadyCSS.nativeShadow&&n.content.appendChild(n.content.querySelector("style"))}(c,p),f.removeChild(d),null===(s=e.ShadyCSS)||void 0===s?void 0:s.nativeShadow){var m=p.content.querySelector("style");null!==m&&f.appendChild(m.cloneNode(!0))}h.insertBefore(f,y),this.ΞA=w,this.ΞB=y}else a.call(this,i,n)},s.ΞC=function(n){var t,o=null===(t=this.options)||void 0===t?void 0:t.scope,e=u.get(o);void 0===e&&u.set(o,e=new Map);var v=e.get(n.strings);return void 0===v&&e.set(n.strings,v=new i(n,this.options)),v}}})})),null!==(n=(t=globalThis).litElementPlatformSupport)&&void 0!==n||(t.litElementPlatformSupport=function(i){var n=i.LitElement,t=window;if(void 0!==t.ShadyCSS&&(!t.ShadyCSS.nativeShadow||t.ShadyCSS.ApplyShim)){n.ΞJ=!0;var o=n.prototype,e=o.createRenderRoot;o.createRenderRoot=function(){return this.renderOptions.scope=this.localName,e.call(this)}}})},"function"==typeof define&&define.amd?define(i):i()}));
//# sourceMappingURL=polyfill-support.js.map
