!function(i){"function"==typeof define&&define.amd?define(i):i()}((function(){"use strict";var i;i=function(){var i,n,t;i=function(){
/**
                    * @license
                    * Copyright 2017 Google LLC
                    * SPDX-License-Identifier: BSD-3-Clause
                    */
var i,n,t="__scoped";null!==(i=(n=globalThis).reactiveElementPlatformSupport)&&void 0!==i||(n.reactiveElementPlatformSupport=function(i){var n=i.ReactiveElement,o=window;if(void 0!==o.ShadyCSS&&(!o.ShadyCSS.nativeShadow||o.ShadyCSS.ApplyShim)){var e=n.prototype;o.ShadyDOM&&o.ShadyDOM.inUse&&!0===o.ShadyDOM.noPatch&&o.ShadyDOM.patchElementProto(e);var u=e.createRenderRoot;e.createRenderRoot=function(){var i,n,e,v=this.localName;if(o.ShadyCSS.nativeShadow)return u.call(this);if(!this.constructor.hasOwnProperty(t)){this.constructor[t]=!0;var r=this.constructor.elementStyles.map((function(i){return i instanceof CSSStyleSheet?Array.from(i.cssRules).reduce((function(i,n){return i+n.cssText}),""):i.cssText}));null===(n=null===(i=o.ShadyCSS)||void 0===i?void 0:i.ScopingShim)||void 0===n||n.prepareAdoptedCssText(r,v),void 0===this.constructor._$AJ&&o.ShadyCSS.prepareTemplateStyles(document.createElement("template"),v)}return null!==(e=this.shadowRoot)&&void 0!==e?e:this.attachShadow(this.constructor.shadowRootOptions)};var v=e.connectedCallback;e.connectedCallback=function(){v.call(this),this.hasUpdated&&o.ShadyCSS.styleElement(this)};var r=e._$AE;e._$AE=function(i){this.hasUpdated||o.ShadyCSS.styleElement(this),r.call(this,i)}}})},"function"==typeof define&&define.amd?define(i):i(),function(i){"function"==typeof define&&define.amd?define(i):i()}((function(){
/**
                    * @license
                    * Copyright 2017 Google LLC
                    * SPDX-License-Identifier: BSD-3-Clause
                    */
var i,n,t=new Set,o=new Map;null!==(i=(n=globalThis).litHtmlPlatformSupport)&&void 0!==i||(n.litHtmlPlatformSupport=function(i,n){var e=window;if(void 0!==e.ShadyCSS&&(!e.ShadyCSS.nativeShadow||e.ShadyCSS.ApplyShim)){var u=function(i){return void 0!==i&&!t.has(i)},v=function(i){var n=o.get(i);return void 0===n&&o.set(i,n=[]),n},r=new Map,f=i.createElement;i.createElement=function(n,t){var o=f.call(i,n,t),r=null==t?void 0:t.scope;if(void 0!==r&&(e.ShadyCSS.nativeShadow||e.ShadyCSS.prepareTemplateDom(o,r),u(r))){var d=v(r),s=o.content.querySelectorAll("style");d.push.apply(d,Array.from(s).map((function(i){var n;return null===(n=i.parentNode)||void 0===n||n.removeChild(i),i.textContent})))}return o};var d=document.createDocumentFragment(),s=document.createComment(""),l=n.prototype,a=l._$AI;l._$AI=function(i,n){var r,f,l;void 0===n&&(n=this);var h=this._$AA.parentNode,c=null===(r=this.options)||void 0===r?void 0:r.scope;if(h instanceof ShadowRoot&&u(c)){var w=this._$AA,y=this._$AB;d.appendChild(s),this._$AA=s,this._$AB=null,a.call(this,i,n);var p=(null===(f=i)||void 0===f?void 0:f._$litType$)?this._$AH._$AD.el:document.createElement("template");if(function(i,n){var u,r=v(i),f=0!==r.length;f&&((u=document.createElement("style")).textContent=r.join("\n"),n.content.appendChild(u)),t.add(i),o.delete(i),e.ShadyCSS.prepareTemplateStyles(n,i),f&&e.ShadyCSS.nativeShadow&&null!==(u=n.content.querySelector("style"))&&n.content.appendChild(u)}(c,p),d.removeChild(s),null===(l=e.ShadyCSS)||void 0===l?void 0:l.nativeShadow){var m=p.content.querySelector("style");null!==m&&d.appendChild(m.cloneNode(!0))}h.insertBefore(d,y),this._$AA=w,this._$AB=y}else a.call(this,i,n)},l._$AC=function(n){var t,o=null===(t=this.options)||void 0===t?void 0:t.scope,e=r.get(o);void 0===e&&r.set(o,e=new Map);var u=e.get(n.strings);return void 0===u&&e.set(n.strings,u=new i(n,this.options)),u}}})})),null!==(n=(t=globalThis).litElementPlatformSupport)&&void 0!==n||(t.litElementPlatformSupport=function(i){var n=i.LitElement,t=window;if(void 0!==t.ShadyCSS&&(!t.ShadyCSS.nativeShadow||t.ShadyCSS.ApplyShim)){n._$AJ=!0;var o=n.prototype,e=o.createRenderRoot;o.createRenderRoot=function(){return this.renderOptions.scope=this.localName,e.call(this)}}})},"function"==typeof define&&define.amd?define(i):i()}));
//# sourceMappingURL=polyfill-support.js.map
